#!/bin/bash

text=${1:-MEAT.}
name=${2:-}
[ -z "$name" ] && {
    name=$(date "+%s")
}

docker run -it \
    -e "TEXT=${text}" \
    -e "WIDTH=4000" \
    -e "HEIGHT=1200" \
    -e "OUTER_FONT_SIZE=950" \
    -e "HORIZ=0.6" \
    -e "MAX_SIZE=20" \
    -e "MIN_SIZE=10" \
    -v "$PWD/in:/opt/in" \
    -v "$PWD/out:/opt/out" \
    meatcloud

convert $PWD/out/meat.png -trim $PWD/out/meat.png
cp $PWD/out/meat.png $PWD/out/${name}.png
