#!/bin/bash

min=${1:-10}
max=${2:-25}


name=${3:-}
[ -z "$name" ] && {
    name=$(date "+%s")
}

docker run -it \
    -e "HORIZ=0.7" \
    -e "MAX_SIZE=$max" \
    -e "MIN_SIZE=$min" \
    -v "$PWD/in:/opt/in" \
    -v "$PWD/out:/opt/out" \
    meatcloud

out="$PWD/out/meat.png"
convert "$out" -trim "$out"
cp $out $PWD/out/${name}.png
