#!/bin/bash

min=${1:-10}
max=${2:-25}
rel_scale=${3:-0.5}
horiz=${4:-0.7}
name=$(date "+%s")

docker run -it \
    -e "HORIZ=$horiz" \
    -e "REL_SCALE=$rel_scale" \
    -e "MAX_SIZE=$max" \
    -e "MIN_SIZE=$min" \
    -v "$PWD/in:/opt/in" \
    -v "$PWD/out:/opt/out" \
    meatcloud

out="$PWD/out/meat_txt.png"
outline="$PWD/in/outline.png"
final="$PWD/out/meat.png"

convert "$out" -fuzz 90% -transparent black "$out"
composite -gravity center "$outline" "$out" "$final"

cp $final $PWD/out/${name}.png
